### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Jasmin61213**
傅雅得
http://52.196.101.116:3000/api/attractions?page=1 
http://52.196.101.116:3000/api/attractions?page=0&keyword=藝文館所 
http://52.196.101.116:3000/api/attractions?page=0&keyword=北 
http://52.196.101.116:3000/api/attraction/10

### CODE REVIEW

**Comment by cwpeng** [comment]
Please request review explicitly from the right side in this page.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost Done. But 1 issue:

"images" field of attraction should be a string array containing every image URLs. For example: `["Image URL 1", "Image URL 2", ...]`. But yours is actually a string `"['Image URL 1', 'Image URL 2', ...]"`

Fix this issue and re-request review.

**Comment by Jasmin61213** [comment]
Already fixed the issue.

**Review by cwpeng — APPROVED** [review]
OK. Good. :)

**Pull request merged**
