### PR TITLE
feat/TapPay.api pay by prime

### PR DESCRIPTION
**Pull request by Jasmin61213**
傅雅得
http://52.196.101.116:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should delete booking data after successful ordering.

**Comment by Jasmin61213** [comment]
Already fixed the issue.

**Review by cwpeng — APPROVED** [review]
Good. Done. Look forward to your member page for profile management and historical orders.

**Comment by Jasmin61213** [comment]
Thanks! :)))

**Pull request merged**
