### PR TITLE
feat/index.html fetch api

### PR DESCRIPTION
**Pull request by Jasmin61213**
傅雅得
http://52.196.101.116:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout issues: border style of attraction and head title in mobile version should keep in the same line.

**Comment by Jasmin61213** [comment]
Already fixed layout  issues.

**Review by cwpeng — APPROVED** [review]
OK. Done.

Suggest investigating how to apply CSS position:relative and position:absolute in our layout.

**Comment by Jasmin61213** [comment]
Ok! Thanks:)

**Pull request merged**
