### PR TITLE
feat/booking.api

### PR DESCRIPTION
**Pull request by Jasmin61213**
傅雅得
http://52.196.101.116:3000/
http://52.196.101.116:3000/attraction/5
http://52.196.101.116:3000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Position of delete icon does not aligh with design in the mobile version.

**Comment by Jasmin61213** [comment]
Already fixed mobile version.

**Review by cwpeng — APPROVED** [review]
Date validation is good. Done.

**Comment by Jasmin61213** [comment]
Thanks! :))

**Pull request merged**
